version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-web-truyen
    restart: always
    ports:
      - "27017:27017" # Map cổng mặc định của MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db # Lưu dữ liệu MongoDB ra volume

volumes:
  mongo-data:
